format = """
[](#f38ba8)\
$username\
[](fg:#f38ba8 bg:#cdd6f4)\
$directory\
[ ](fg:#cdd6f4)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "fg:#181825 bg:#f38ba8"
style_root = "bg:#fe640b"
format = '[$user ]($style)'

[directory]
style = "fg:#11111b bg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "

