import = [
	"~/.config/alacritty/catppuccin-mocha.toml"	
]


[env]
TERM = "xterm-256color"


[window]

opacity = 0.8


[font]

normal = { family = "Hack Nerd Font" }

bold = { family = "Hack Nerd Font" }

italic = { family = "Hack Nerd Font" }

bold_italic = { family = "Hack Nerd Font" }

size = 8


[mouse]

hide_when_typing = true
